# Default server configuration for serving static files in the docker container
server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html; # This is for React Router SPA to work
    }
}
